// Auto-generated by testnet_deploy_and_wire_frontend.sh
// DO NOT EDIT MANUALLY
// Deployed at: 2026-01-10T22:54:10Z

export const generatedConfig = {
  chainName: 'casper-test',
  nodeUrl: 'https://node.testnet.casper.network',
  // Deprecated in staking-based version (kept for backwards compatibility).
  tcsprContractHash: '',
  mcsprContractHash: 'Contract(ContractPackageHash(e8fa988e89d6c7d1abac54de32e61bca28ac9bedc689f556d8256bf6e14dfbd4))',
  magniContractHash: 'Contract(ContractPackageHash(7b56884aebc6e9cb3cc495f42cfc99a56be73b96c32fadf9931c0f205a29ef5f))',
  defaultValidatorPublicKey: '012b365e09c5d75187b4abc25c4aa28109133bab6a256ef4abe24348073e590d80',
  deployedAt: '2026-01-10T22:54:10Z',
} as const;

export default generatedConfig;
