// Auto-generated by testnet_deploy_and_wire_frontend.sh
// DO NOT EDIT MANUALLY
// Deployed at: 2026-01-10T09:15:29Z

export const generatedConfig = {
  chainName: 'casper-test',
  nodeUrl: 'https://node.testnet.casper.network',
  // Deprecated in staking-based version (kept for backwards compatibility).
  tcsprContractHash: '',
  mcsprContractHash: 'Contract(ContractPackageHash(345ef050546b07564f2e4cd33aa7b1a2f6f798f53ff9cd807f1fa407a1507f02))',
  magniContractHash: 'Contract(ContractPackageHash(84457f7cc823c97a1443cc95e5826fba4a0c41f5ff150279f5414778da2fa3ba))',
  defaultValidatorPublicKey: '012b365e09c5d75187b4abc25c4aa28109133bab6a256ef4abe24348073e590d80',
  deployedAt: '2026-01-10T09:15:29Z',
} as const;

export default generatedConfig;
