// Auto-generated by testnet_deploy_and_wire_frontend.sh
// DO NOT EDIT MANUALLY
// Deployed at: 2026-01-15T22:55:46Z

export const generatedConfig = {
  chainName: 'casper-test',
  nodeUrl: 'https://node.testnet.casper.network',
  // Deprecated in staking-based version (kept for backwards compatibility).
  tcsprContractHash: '',
  mcsprContractHash: 'd7f571a31d5fc7f6a3abd7d8a501ed7243b60fe950dd328aa90805ccae719ef8',
  magniContractHash: 'aecf3a9598a7a5bf27411aaae982bbadd881172006a06ef388a5d6f6e33c309c',
  defaultValidatorPublicKey: '012b365e09c5d75187b4abc25c4aa28109133bab6a256ef4abe24348073e590d80',
  deployedAt: '2026-01-15T22:55:46Z',
} as const;

export default generatedConfig;
